# 帖子地址
thread-url: 'https://www.minebbs.com/threads/XXX'
headers:
  User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0'
# 匹配时间戳的正则表达式
# 如果不懂请勿修改
matcher:
  regex: 'data-time="([0-9]+)" data-date-string.*datePublished'
  find-times: 1
  group: 1
# 时间设定
time:
  # 顶帖后限定领取奖励的时间 (秒)
  top-timeout: 60
  # 两次顶帖间的冷却时间 (秒)
  top-cooldown: 7200
  # reward 命令冷却时间 (秒)
  reward-cooldown: 7200
  # 两贴顶帖间冷却时间检查机制
  # true - 以玩家获得奖励算作成功顶帖
  # false - 以顶帖时间更新算作成功顶帖
  # 顶帖时间更新后，将会记录一个 last time
  # 玩家顶帖成功获得后，将会记录一个 last success time
  # true 用 last success time 计算冷却，反之用 last time 计算冷却
  # 设置为 true 会对玩家更友好，不会出现“不是本服玩家顶帖也会卡冷却时间”的问题
  check-only-success: false

# 奖励命令，支持 PAPI
# [console]控制台命令
# [player]玩家命令
# [message]输出聊天消息
reward-commands:
  - '[console]money give %player_name% 100 顶帖奖励'
  - '[message]&7[&e&l顶帖奖励&7] &a你成功领取了顶帖奖励!'

messages:
  help:
    - '&e&lMineBBS顶帖奖励'
    - '  &f/mbr reward &7请求领取顶帖奖励'
  time:
    hours: '时'
    hour: '时'
    minute: '分'
    minutes: '分'
    second: '秒'
    seconds: '秒'
  request-fail: '&7[&e&l顶帖奖励&7] &e顶帖信息获取失败，请稍候再试'
  top-timeout: '&7[&e&l顶帖奖励&7] &e领取超时，请在顶帖后 &b%time% &e内领取奖励'
  top-cooldown: '&7[&e&l顶帖奖励&7] &e顶帖奖励正在冷却中 &7(剩余 &f%remain%&7)'
  reward-cooldown: '&7[&e&l顶帖奖励&7] &e命令正在冷却中 &7(剩余 &f%remain%&7)'
  reload: '&7[&e&l顶帖奖励&7] &a配置文件已重载'
